# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x66ileService.proto\"<\n\x08\x46ileData\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\'\n\x03\x61\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x08\x46ileInfo\x12\x1c\n\tuser_info\x18\x01 \x01(\x0b\x32\t.UserInfo\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\x1c\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\"%\n\x10\x46ileListResponse\x12\x11\n\tfilenames\x18\x01 \x01(\t\"\x12\n\x10HeartbeatRequest\"%\n\x11HeartbeatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x0e\n\x0cStatsRequest\"5\n\rStatsResponse\x12\x0f\n\x07\x63puutil\x18\x01 \x01(\x02\x12\x13\n\x0bswap_memory\x18\x02 \x01(\x02\"\x0e\n\x0cUsersRequest\"#\n\rUsersResponse\x12\x12\n\nusers_list\x18\x01 \x01(\t\"<\n\x0b\x43lusterInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x03 \x01(\t\"G\n\x0c\x43lusterStats\x12\x11\n\tcpu_usage\x18\x01 \x01(\t\x12\x12\n\ndisk_space\x18\x02 \x01(\t\x12\x10\n\x08used_mem\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\xed\x03\n\x0b\x46ileService\x12(\n\x0c\x44ownloadFile\x12\t.FileInfo\x1a\t.FileData\"\x00\x30\x01\x12\x1f\n\nFileSearch\x12\t.FileInfo\x1a\x04.ack\"\x00\x12*\n\x08\x46ileList\x12\t.UserInfo\x1a\x11.FileListResponse\"\x00\x12$\n\rReplicateFile\x12\t.FileData\x1a\x04.ack\"\x00(\x01\x12!\n\nUploadFile\x12\t.FileData\x1a\x04.ack\"\x00(\x01\x12\x1f\n\nFileDelete\x12\t.FileInfo\x1a\x04.ack\"\x00\x12!\n\nUpdateFile\x12\t.FileData\x1a\x04.ack\"\x00(\x01\x12\x34\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\"\x00\x12(\n\x05Stats\x12\r.StatsRequest\x1a\x0e.StatsResponse\"\x00\x12+\n\x08GetUsers\x12\r.UsersRequest\x1a\x0e.UsersResponse\"\x00\x12(\n\x0fgetClusterStats\x12\x06.Empty\x1a\r.ClusterStats\x12#\n\rgetLeaderInfo\x12\x0c.ClusterInfo\x1a\x04.ackb\x06proto3')
)




_FILEDATA = _descriptor.Descriptor(
  name='FileData',
  full_name='FileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='FileData.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='FileData.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='FileData.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=81,
)


_ACK = _descriptor.Descriptor(
  name='ack',
  full_name='ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ack.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ack.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=122,
)


_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_info', full_name='FileInfo.user_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='FileInfo.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=182,
)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='UserInfo.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=212,
)


_FILELISTRESPONSE = _descriptor.Descriptor(
  name='FileListResponse',
  full_name='FileListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filenames', full_name='FileListResponse.filenames', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=251,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=271,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='HeartbeatResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=310,
)


_STATSREQUEST = _descriptor.Descriptor(
  name='StatsRequest',
  full_name='StatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=326,
)


_STATSRESPONSE = _descriptor.Descriptor(
  name='StatsResponse',
  full_name='StatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpuutil', full_name='StatsResponse.cpuutil', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='swap_memory', full_name='StatsResponse.swap_memory', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=381,
)


_USERSREQUEST = _descriptor.Descriptor(
  name='UsersRequest',
  full_name='UsersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=397,
)


_USERSRESPONSE = _descriptor.Descriptor(
  name='UsersResponse',
  full_name='UsersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users_list', full_name='UsersResponse.users_list', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=434,
)


_CLUSTERINFO = _descriptor.Descriptor(
  name='ClusterInfo',
  full_name='ClusterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ClusterInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ClusterInfo.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='ClusterInfo.clusterName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=496,
)


_CLUSTERSTATS = _descriptor.Descriptor(
  name='ClusterStats',
  full_name='ClusterStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='ClusterStats.cpu_usage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_space', full_name='ClusterStats.disk_space', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='used_mem', full_name='ClusterStats.used_mem', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=569,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=578,
)

_FILEINFO.fields_by_name['user_info'].message_type = _USERINFO
DESCRIPTOR.message_types_by_name['FileData'] = _FILEDATA
DESCRIPTOR.message_types_by_name['ack'] = _ACK
DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['FileListResponse'] = _FILELISTRESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
DESCRIPTOR.message_types_by_name['StatsRequest'] = _STATSREQUEST
DESCRIPTOR.message_types_by_name['StatsResponse'] = _STATSRESPONSE
DESCRIPTOR.message_types_by_name['UsersRequest'] = _USERSREQUEST
DESCRIPTOR.message_types_by_name['UsersResponse'] = _USERSRESPONSE
DESCRIPTOR.message_types_by_name['ClusterInfo'] = _CLUSTERINFO
DESCRIPTOR.message_types_by_name['ClusterStats'] = _CLUSTERSTATS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), dict(
  DESCRIPTOR = _FILEDATA,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:FileData)
  ))
_sym_db.RegisterMessage(FileData)

ack = _reflection.GeneratedProtocolMessageType('ack', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:ack)
  ))
_sym_db.RegisterMessage(ack)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), dict(
  DESCRIPTOR = _FILEINFO,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:FileInfo)
  ))
_sym_db.RegisterMessage(FileInfo)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERINFO,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo)
  ))
_sym_db.RegisterMessage(UserInfo)

FileListResponse = _reflection.GeneratedProtocolMessageType('FileListResponse', (_message.Message,), dict(
  DESCRIPTOR = _FILELISTRESPONSE,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:FileListResponse)
  ))
_sym_db.RegisterMessage(FileListResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATREQUEST,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:HeartbeatRequest)
  ))
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATRESPONSE,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:HeartbeatResponse)
  ))
_sym_db.RegisterMessage(HeartbeatResponse)

StatsRequest = _reflection.GeneratedProtocolMessageType('StatsRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATSREQUEST,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:StatsRequest)
  ))
_sym_db.RegisterMessage(StatsRequest)

StatsResponse = _reflection.GeneratedProtocolMessageType('StatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATSRESPONSE,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:StatsResponse)
  ))
_sym_db.RegisterMessage(StatsResponse)

UsersRequest = _reflection.GeneratedProtocolMessageType('UsersRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERSREQUEST,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:UsersRequest)
  ))
_sym_db.RegisterMessage(UsersRequest)

UsersResponse = _reflection.GeneratedProtocolMessageType('UsersResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERSRESPONSE,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:UsersResponse)
  ))
_sym_db.RegisterMessage(UsersResponse)

ClusterInfo = _reflection.GeneratedProtocolMessageType('ClusterInfo', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERINFO,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:ClusterInfo)
  ))
_sym_db.RegisterMessage(ClusterInfo)

ClusterStats = _reflection.GeneratedProtocolMessageType('ClusterStats', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERSTATS,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:ClusterStats)
  ))
_sym_db.RegisterMessage(ClusterStats)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'fileService_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)



_FILESERVICE = _descriptor.ServiceDescriptor(
  name='FileService',
  full_name='FileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=581,
  serialized_end=1074,
  methods=[
  _descriptor.MethodDescriptor(
    name='DownloadFile',
    full_name='FileService.DownloadFile',
    index=0,
    containing_service=None,
    input_type=_FILEINFO,
    output_type=_FILEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FileSearch',
    full_name='FileService.FileSearch',
    index=1,
    containing_service=None,
    input_type=_FILEINFO,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FileList',
    full_name='FileService.FileList',
    index=2,
    containing_service=None,
    input_type=_USERINFO,
    output_type=_FILELISTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReplicateFile',
    full_name='FileService.ReplicateFile',
    index=3,
    containing_service=None,
    input_type=_FILEDATA,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UploadFile',
    full_name='FileService.UploadFile',
    index=4,
    containing_service=None,
    input_type=_FILEDATA,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FileDelete',
    full_name='FileService.FileDelete',
    index=5,
    containing_service=None,
    input_type=_FILEINFO,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFile',
    full_name='FileService.UpdateFile',
    index=6,
    containing_service=None,
    input_type=_FILEDATA,
    output_type=_ACK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='FileService.Heartbeat',
    index=7,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_HEARTBEATRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stats',
    full_name='FileService.Stats',
    index=8,
    containing_service=None,
    input_type=_STATSREQUEST,
    output_type=_STATSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='FileService.GetUsers',
    index=9,
    containing_service=None,
    input_type=_USERSREQUEST,
    output_type=_USERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getClusterStats',
    full_name='FileService.getClusterStats',
    index=10,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CLUSTERSTATS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getLeaderInfo',
    full_name='FileService.getLeaderInfo',
    index=11,
    containing_service=None,
    input_type=_CLUSTERINFO,
    output_type=_ACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVICE)

DESCRIPTOR.services_by_name['FileService'] = _FILESERVICE

# @@protoc_insertion_point(module_scope)
