# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import monitor.proto.hearbeat_pb2 as hearbeat__pb2

class HearBeatServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.isAlive = channel.unary_unary(
        '/HearBeatService/isAlive',
        request_serializer=hearbeat__pb2.NodeInfo.SerializeToString,
        response_deserializer=hearbeat__pb2.Stats.FromString,
        )


class HearBeatServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def isAlive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HearBeatServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'isAlive': grpc.unary_unary_rpc_method_handler(
          servicer.isAlive,
          request_deserializer=hearbeat__pb2.NodeInfo.FromString,
          response_serializer=hearbeat__pb2.Stats.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HearBeatService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
