# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fileservice_pb2 as fileservice__pb2


class FileGetServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DownloadFile = channel.unary_stream(
        '/FileGetService/DownloadFile',
        request_serializer=fileservice__pb2.FileInfo.SerializeToString,
        response_deserializer=fileservice__pb2.FileData.FromString,
        )
    self.FileSearch = channel.unary_unary(
        '/FileGetService/FileSearch',
        request_serializer=fileservice__pb2.FileInfo.SerializeToString,
        response_deserializer=fileservice__pb2.ack.FromString,
        )
    self.FileList = channel.unary_unary(
        '/FileGetService/FileList',
        request_serializer=fileservice__pb2.UserInfo.SerializeToString,
        response_deserializer=fileservice__pb2.FileListResponse.FromString,
        )


class FileGetServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DownloadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FileSearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FileList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileGetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DownloadFile': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadFile,
          request_deserializer=fileservice__pb2.FileInfo.FromString,
          response_serializer=fileservice__pb2.FileData.SerializeToString,
      ),
      'FileSearch': grpc.unary_unary_rpc_method_handler(
          servicer.FileSearch,
          request_deserializer=fileservice__pb2.FileInfo.FromString,
          response_serializer=fileservice__pb2.ack.SerializeToString,
      ),
      'FileList': grpc.unary_unary_rpc_method_handler(
          servicer.FileList,
          request_deserializer=fileservice__pb2.UserInfo.FromString,
          response_serializer=fileservice__pb2.FileListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileGetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class FileInternalServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReplicateFile = channel.stream_unary(
        '/FileInternalService/ReplicateFile',
        request_serializer=fileservice__pb2.FileData.SerializeToString,
        response_deserializer=fileservice__pb2.ack.FromString,
        )


class FileInternalServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReplicateFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileInternalServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReplicateFile': grpc.stream_unary_rpc_method_handler(
          servicer.ReplicateFile,
          request_deserializer=fileservice__pb2.FileData.FromString,
          response_serializer=fileservice__pb2.ack.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileInternalService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class FilePostServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UploadFile = channel.stream_unary(
        '/FilePostService/UploadFile',
        request_serializer=fileservice__pb2.FileData.SerializeToString,
        response_deserializer=fileservice__pb2.ack.FromString,
        )
    self.FileDelete = channel.unary_unary(
        '/FilePostService/FileDelete',
        request_serializer=fileservice__pb2.FileInfo.SerializeToString,
        response_deserializer=fileservice__pb2.ack.FromString,
        )
    self.UpdateFile = channel.stream_unary(
        '/FilePostService/UpdateFile',
        request_serializer=fileservice__pb2.FileData.SerializeToString,
        response_deserializer=fileservice__pb2.ack.FromString,
        )


class FilePostServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UploadFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FileDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FilePostServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UploadFile': grpc.stream_unary_rpc_method_handler(
          servicer.UploadFile,
          request_deserializer=fileservice__pb2.FileData.FromString,
          response_serializer=fileservice__pb2.ack.SerializeToString,
      ),
      'FileDelete': grpc.unary_unary_rpc_method_handler(
          servicer.FileDelete,
          request_deserializer=fileservice__pb2.FileInfo.FromString,
          response_serializer=fileservice__pb2.ack.SerializeToString,
      ),
      'UpdateFile': grpc.stream_unary_rpc_method_handler(
          servicer.UpdateFile,
          request_deserializer=fileservice__pb2.FileData.FromString,
          response_serializer=fileservice__pb2.ack.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FilePostService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
